services:
  - type: web
    name: New_Project_CNPM_backend
    env: node
    plan: free
    branch: main
    repo: https://github.com/ngDuyHung/New_Project_CNPM
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: CORS_ORIGIN
        value: https://cnpm.duyhung.io.vn
      - key: DB_HOST
        value: 160.191.243.16
      - key: DB_NAME
        value: t1756395750_cnpm_nam3_hocky2_2025
      - key: DB_PASSWORD
        value: t1756395750_cnpm_nam3_hocky2_2025
      - key: DB_USER
        value: t1756395750_cnpm_nam3_hocky2_2025
      - key: GEMINI_API_KEY
        value: AIzaSyAo8UhFCyLSh6DHCjKgnWwoVMz0Af6-AFc
      - key: JWT_SECRET
        value: EnglishLearning_HDPTAK_Secret_Key_2024!@
      - key: NODE_ENV
        value: production
